version: '0.1'
services:
  server:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
  
  postgres:
    image: postgres:16.2-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: